### ISSUE TITLE
No such file or directory　when running on mac

### ISSUE THREAD

**Issue by fucusy** [moxiegushi/zhihu#4]
['11.png', '44.png', '73.png', '106.png']
Traceback (most recent call last):
  File "zhihu.py", line 180, in <module>
    state = login()
  File "zhihu.py", line 63, in login
    data['captcha'] = predict(cropModel,classModel)
  File "zhihu.py", line 121, in predict
    temp.save('./tobe_classfied/data/' + each)
  File "/Library/Python/2.7/site-packages/PIL/Image.py", line 1659, in save
    fp = builtins.open(filename, "wb")
IOError: [Errno 2] No such file or directory: './tobe_classfied/data/11.png'

**Comment by moxiegushi** [comment]
关于tobe_classfied目录的问题，已经提交了修改，感谢关注 : )  有问题大家一起讨论～
