### ISSUE TITLE
Error running on Ubuntu 12.04 with GPU support

### ISSUE THREAD

**Issue by fucusy** [moxiegushi/zhihu#5]
Traceback (most recent call last):
  File "zhihu.py", line 180, in <module>
    state = login()
  File "zhihu.py", line 63, in login
    data['captcha'] = predict(cropModel,classModel)
  File "zhihu.py", line 94, in predict
    predictCrop = cropModel.predict_generator(cropGenerator,121)
  File "/usr/local/lib/python2.7/dist-packages/Keras-1.1.2-py2.7.egg/keras/models.py", line 981, in predict_generator
    pickle_safe=pickle_safe)
  File "/usr/local/lib/python2.7/dist-packages/Keras-1.1.2-py2.7.egg/keras/engine/training.py", line 1652, in predict_generator
    outs = self.predict_on_batch(x)
  File "/usr/local/lib/python2.7/dist-packages/Keras-1.1.2-py2.7.egg/keras/engine/training.py", line 1273, in predict_on_batch
    self.internal_input_shapes)
  File "/usr/local/lib/python2.7/dist-packages/Keras-1.1.2-py2.7.egg/keras/engine/training.py", line 73, in standardize_input_data
    'Found: ' + str(data)[:200] + '...')
Exception: Error when checking : data should be a Numpy array, or list/dict of Numpy arrays. Found: None...

**Comment by moxiegushi** [comment]
错误出在captchaTemp/data目录下没有找到切割好的图片，可以测试一下crop函数的结果，正确的结果应该是在该目录下存在121张图片，在我的机器上没能复现这个错误，不好意思，我也是初学者，相互学习: )
